// <auto-generated />
using System;
using Consultorio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Consultorio.Migrations
{
    [DbContext(typeof(ConsultorioContext))]
    [Migration("20220726114616_chengeNameCol")]
    partial class chengeNameCol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Consultorio.Models.Entities.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TEXT")
                        .HasColumnName("horario");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomePaciente");

                    b.HasKey("Id");

                    b.ToTable("tb_agendamento");
                });
#pragma warning restore 612, 618
        }
    }
}
